name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write     # necesario para pypa/gh‑action‑pypi‑publish

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build (sdist + wheel)
        run: |
          python -m pip install --upgrade build
          python -m build -s -w python   # genera dist/ en python/dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist
          password: ${{ secrets.PYPI_API_TOKEN }}
